### ISSUE TITLE
Issues runing example files

### ISSUE THREAD

**Issue by fangbohao** [EVidenceModeler/EVidenceModeler#66]
Hi, I am trying to run EVM singularity on the example files under the 'testing' folder. However, I get an error message shown below. Could you please help to find out what is the problem? Thanks!

Command line: 
`singularity exec /n/home00/bfang/programs/EVM/EVidenceModeler.v2.0.0.simg EVidenceModeler \
--sample_id smalltest.singularity \
--genome genome.fasta \
--weights weights.txt \
--gene_predictions gene_predictions.gff3 \
--protein_alignments protein_alignments.gff3 \
--transcript_alignments transcript_alignments.gff3 \
--segmentSize 100000 \
--overlapSize 10000`

Error message:
`singularity exec /n/home00/bfang/programs/EVM/EVidenceModeler.v2.0.0.simg EVidenceModeler --sample_id smalltest.singularity --genome genome.fasta --weights weights.txt --gene_predictions gene_predictions.gff3 --protein_alignments protein_alignments.gff3 --transcript_alignments transcript_alignments.gff3 --segmentSize 100000 --overlapSize 10000
* [Fri Jan 20 15:26:44 2023] Running CMD: /usr/local/bin/EvmUtils/partition_EVM_inputs.pl  --partition_dir smalltest.singularity.partitions  --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta  --gene_predictions /n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3  --protein_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/protein_alignments.gff3  --transcript_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/transcript_alignments.gff3  --segmentSize 100000 --overlapSize 10000  --partition_listing smalltest.singularity.partitions.listing
writing /n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3 for Contig1
-writing genome seqs for Contig1
Contig1 has 1 partitions.
* [Fri Jan 20 15:26:44 2023] Running CMD: /usr/local/bin/EvmUtils/write_EVM_commands.pl  --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta  --weights /n/home00/bfang/programs/EVM/EVidenceModeler/testing/weights.txt  --gene_predictions /n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3  --protein_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/protein_alignments.gff3  --transcript_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/transcript_alignments.gff3  --min_intron_length 20  --terminal_intergenic_re_search 10000  --output_file_name evm.out  --partitions smalltest.singularity.partitions.listing  > smalltest.singularity.partitions.evm_cmds
* [Fri Jan 20 15:26:44 2023] Running CMD: /usr/local/bin/plugins/ParaFly/bin/ParaFly -c smalltest.singularity.partitions.evm_cmds -CPU 4 -vv -max_retry 1 -failed_cmds smalltest.singularity.failed_cmds -shuffle 
warning, command: /usr/local/bin/EvmUtils/evidence_modeler.pl -G genome.fasta -g gene_predictions.gff3 -w /n/home00/bfang/programs/EVM/EVidenceModeler/testing/weights.txt -e transcript_alignments.gff3  -p protein_alignments.gff3  --min_intron_length 20  --terminal_intergenic_re_search 10000  --exec_dir smalltest.singularity.partitions/Contig1 > smalltest.singularity.partitions/Contig1/evm.out 2> smalltest.singularity.partitions/Contig1/evm.out.log has successfully completed from a previous run.  Skipping it here.
Number of Commands: 0

All commands completed successfully. :-)

* [Fri Jan 20 15:26:44 2023] Running CMD: /usr/local/bin/EvmUtils/recombine_EVM_partial_outputs.pl --partitions smalltest.singularity.partitions.listing --output_file_name evm.out
* [Fri Jan 20 15:26:44 2023] Running CMD: /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl  --partitions smalltest.singularity.partitions.listing  --output evm.out  --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta
// Processing Contig1, smalltest.singularity.partitions/Contig1
Error, cannot open smalltest.singularity.partitions/Contig1/evm.out
Error, cmd /usr/local/bin/EvmUtils/EVM_to_GFF3.pl smalltest.singularity.partitions/Contig1/evm.out Contig1 > smalltest.singularity.partitions/Contig1/evm.out.gff3 died with ret 512  at /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl line 64.
Error, cmd: /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl  --partitions smalltest.singularity.partitions.listing  --output evm.out  --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta died with ret 512 No such file or directory at /usr/local/bin/PerlLib/Pipeliner.pm line 187.
        Pipeliner::run(Pipeliner=HASH(0x557a6c3ea2c8)) called at /usr/local/bin/EVidenceModeler line 365
        `

**Comment by brianjohnhaas** [comment]
Hi,

It looks like it's skipping over a step due to a checkpoint.  Try deleting
the directory '__smalltest.singularity-EVM_chckpts/', which stores the
checkpoints, and rerun your singularity command.  Hopefully that fixes it.
If you're doing this in the testing/ directory of the software, then there
should be a cleanMe.sh script that will clean up the directory for you
including removing any earlier checkpoints.

Let's see if that helps.

best,

~brian


On Fri, Jan 20, 2023 at 3:33 PM fangbohao ***@***.***> wrote:
>
> Hi, I am trying to run EVM singularity on the example files under the
'testing' folder. However, I get an error message shown below. Could you
please help to find out what is the problem? Thanks!
>
> Command line:
> singularity exec /n/home00/bfang/programs/EVM/EVidenceModeler.v2.0.0.simg
EVidenceModeler \ --sample_id smalltest.singularity \ --genome genome.fasta
\ --weights weights.txt \ --gene_predictions gene_predictions.gff3 \
--protein_alignments protein_alignments.gff3 \ --transcript_alignments
transcript_alignments.gff3 \ --segmentSize 100000 \ --overlapSize 10000
>
> Error message:
> `singularity exec
/n/home00/bfang/programs/EVM/EVidenceModeler.v2.0.0.simg EVidenceModeler
--sample_id smalltest.singularity --genome genome.fasta --weights
weights.txt --gene_predictions gene_predictions.gff3 --protein_alignments
protein_alignments.gff3 --transcript_alignments transcript_alignments.gff3
--segmentSize 100000 --overlapSize 10000
>
> [Fri Jan 20 15:26:44 2023] Running CMD:
/usr/local/bin/EvmUtils/partition_EVM_inputs.pl --partition_dir
smalltest.singularity.partitions --genome
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta
--gene_predictions
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3
--protein_alignments
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/protein_alignments.gff3
--transcript_alignments
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/transcript_alignments.gff3
--segmentSize 100000 --overlapSize 10000 --partition_listing
smalltest.singularity.partitions.listing
> writing
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3
for Contig1
> -writing genome seqs for Contig1
> Contig1 has 1 partitions.
> [Fri Jan 20 15:26:44 2023] Running CMD:
/usr/local/bin/EvmUtils/write_EVM_commands.pl --genome
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta --weights
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/weights.txt
--gene_predictions
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3
--protein_alignments
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/protein_alignments.gff3
--transcript_alignments
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/transcript_alignments.gff3
--min_intron_length 20 --terminal_intergenic_re_search 10000
--output_file_name evm.out --partitions
smalltest.singularity.partitions.listing >
smalltest.singularity.partitions.evm_cmds
> [Fri Jan 20 15:26:44 2023] Running CMD:
/usr/local/bin/plugins/ParaFly/bin/ParaFly -c
smalltest.singularity.partitions.evm_cmds -CPU 4 -vv -max_retry 1
-failed_cmds smalltest.singularity.failed_cmds -shuffle
> warning, command: /usr/local/bin/EvmUtils/evidence_modeler.pl -G
genome.fasta -g gene_predictions.gff3 -w
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/weights.txt -e
transcript_alignments.gff3 -p protein_alignments.gff3 --min_intron_length
20 --terminal_intergenic_re_search 10000 --exec_dir
smalltest.singularity.partitions/Contig1 >
smalltest.singularity.partitions/Contig1/evm.out 2>
smalltest.singularity.partitions/Contig1/evm.out.log has successfully
completed from a previous run. Skipping it here.
> Number of Commands: 0
>
> All commands completed successfully. :-)
>
> [Fri Jan 20 15:26:44 2023] Running CMD:
/usr/local/bin/EvmUtils/recombine_EVM_partial_outputs.pl --partitions
smalltest.singularity.partitions.listing --output_file_name evm.out
> [Fri Jan 20 15:26:44 2023] Running CMD:
/usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl --partitions
smalltest.singularity.partitions.listing --output evm.out --genome
/n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta
> // Processing Contig1, smalltest.singularity.partitions/Contig1
> Error, cannot open smalltest.singularity.partitions/Contig1/evm.out
> Error, cmd /usr/local/bin/EvmUtils/EVM_to_GFF3.pl
smalltest.singularity.partitions/Contig1/evm.out Contig1 >
smalltest.singularity.partitions/Contig1/evm.out.gff3 died with ret 512 at
/usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl line 64.
> Error, cmd: /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl
--partitions smalltest.singularity.partitions.listing --output evm.out
--genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta
died with ret 512 No such file or directory at
/usr/local/bin/PerlLib/Pipeliner.pm line 187.
> Pipeliner::run(Pipeliner=HASH(0x557a6c3ea2c8)) called at
/usr/local/bin/EVidenceModeler line 365
> `
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by fangbohao** [comment]
> Hi, It looks like it's skipping over a step due to a checkpoint. Try deleting the directory '__smalltest.singularity-EVM_chckpts/', which stores the checkpoints, and rerun your singularity command. Hopefully that fixes it. If you're doing this in the testing/ directory of the software, then there should be a cleanMe.sh script that will clean up the directory for you including removing any earlier checkpoints. Let's see if that helps. best, ~brian
> On Fri, Jan 20, 2023 at 3:33 PM fangbohao ***@***.***> wrote: Hi, I am trying to run EVM singularity on the example files under the
> 'testing' folder. However, I get an error message shown below. Could you please help to find out what is the problem? Thanks!
> Command line: singularity exec /n/home00/bfang/programs/EVM/EVidenceModeler.v2.0.0.simg
> EVidenceModeler \ --sample_id smalltest.singularity \ --genome genome.fasta \ --weights weights.txt \ --gene_predictions gene_predictions.gff3 \ --protein_alignments protein_alignments.gff3 \ --transcript_alignments transcript_alignments.gff3 \ --segmentSize 100000 \ --overlapSize 10000
> Error message: `singularity exec
> /n/home00/bfang/programs/EVM/EVidenceModeler.v2.0.0.simg EVidenceModeler --sample_id smalltest.singularity --genome genome.fasta --weights weights.txt --gene_predictions gene_predictions.gff3 --protein_alignments protein_alignments.gff3 --transcript_alignments transcript_alignments.gff3 --segmentSize 100000 --overlapSize 10000
> [Fri Jan 20 15:26:44 2023] Running CMD:
> /usr/local/bin/EvmUtils/partition_EVM_inputs.pl --partition_dir smalltest.singularity.partitions --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta --gene_predictions /n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3 --protein_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/protein_alignments.gff3 --transcript_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/transcript_alignments.gff3 --segmentSize 100000 --overlapSize 10000 --partition_listing smalltest.singularity.partitions.listing
> writing
> /n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3 for Contig1
> -writing genome seqs for Contig1 Contig1 has 1 partitions. [Fri Jan 20 15:26:44 2023] Running CMD:
> /usr/local/bin/EvmUtils/write_EVM_commands.pl --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta --weights /n/home00/bfang/programs/EVM/EVidenceModeler/testing/weights.txt --gene_predictions /n/home00/bfang/programs/EVM/EVidenceModeler/testing/gene_predictions.gff3 --protein_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/protein_alignments.gff3 --transcript_alignments /n/home00/bfang/programs/EVM/EVidenceModeler/testing/transcript_alignments.gff3 --min_intron_length 20 --terminal_intergenic_re_search 10000 --output_file_name evm.out --partitions smalltest.singularity.partitions.listing > smalltest.singularity.partitions.evm_cmds
> [Fri Jan 20 15:26:44 2023] Running CMD:
> /usr/local/bin/plugins/ParaFly/bin/ParaFly -c smalltest.singularity.partitions.evm_cmds -CPU 4 -vv -max_retry 1 -failed_cmds smalltest.singularity.failed_cmds -shuffle
> warning, command: /usr/local/bin/EvmUtils/evidence_modeler.pl -G
> genome.fasta -g gene_predictions.gff3 -w /n/home00/bfang/programs/EVM/EVidenceModeler/testing/weights.txt -e transcript_alignments.gff3 -p protein_alignments.gff3 --min_intron_length 20 --terminal_intergenic_re_search 10000 --exec_dir smalltest.singularity.partitions/Contig1 > smalltest.singularity.partitions/Contig1/evm.out 2> smalltest.singularity.partitions/Contig1/evm.out.log has successfully completed from a previous run. Skipping it here.
> Number of Commands: 0 All commands completed successfully. :-) [Fri Jan 20 15:26:44 2023] Running CMD:
> /usr/local/bin/EvmUtils/recombine_EVM_partial_outputs.pl --partitions smalltest.singularity.partitions.listing --output_file_name evm.out
> [Fri Jan 20 15:26:44 2023] Running CMD:
> /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl --partitions smalltest.singularity.partitions.listing --output evm.out --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta
> // Processing Contig1, smalltest.singularity.partitions/Contig1 Error, cannot open smalltest.singularity.partitions/Contig1/evm.out Error, cmd /usr/local/bin/EvmUtils/EVM_to_GFF3.pl
> smalltest.singularity.partitions/Contig1/evm.out Contig1 > smalltest.singularity.partitions/Contig1/evm.out.gff3 died with ret 512 at /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl line 64.
> Error, cmd: /usr/local/bin/EvmUtils/convert_EVM_outputs_to_GFF3.pl
> --partitions smalltest.singularity.partitions.listing --output evm.out --genome /n/home00/bfang/programs/EVM/EVidenceModeler/testing/genome.fasta died with ret 512 No such file or directory at /usr/local/bin/PerlLib/Pipeliner.pm line 187.
> Pipeliner::run(Pipeliner=HASH(0x557a6c3ea2c8)) called at
> /usr/local/bin/EVidenceModeler line 365
> ` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
> […](#)
> -- -- Brian J. Haas The Broad Institute http://broadinstitute.org/~bhaas

Hi brian, thank you for your solutions! Now it works with running 'cleanMe.sh' first.

Best wishes,
Bohao
